### ISSUE TITLE
ValueError: could not broadcast input array from shape (122,1) into shape (122)

### ISSUE THREAD

**Issue by mickomicko5573** [gcamfer/Anomaly-ReactionRL#11]
Getting, ValueError: could not broadcast input array from shape (122,1) into shape (122)

For example:
File: \estimators\Simple\AD.py
Line: q_prime = model.predict(next_states)

anaconda + spyder environment
Keras version: (2.2.0)

Thanks.

**Comment by gcamfer** [comment]
Make sure you have the last version and datasets in the correct folder.
It seems that initialization of sequential model is getting the incorrect shape.

I can't replicate your error.

Try now, if error still apearing, I'll study further.

Thanks

**Comment by mickomicko5573** [comment]
Hi, 
Checked now, the code is working very well.
Did you based your project on an article?
Thank you for a great idea and high quality project.
